/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.79.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for a payment's data
type Payment struct {
	// Payment identifier
	Id int64 `json:"id"`
	// Identifier of the account to which this payment relates
	AccountId int64 `json:"accountId"`
	// Payment type
	Type_ string `json:"type"`
	// Total money amount of the payment order(s), as absolute value
	Amount float32 `json:"amount"`
	// Total count of orders included in this payment
	OrderCount int32 `json:"orderCount"`
	// Current payment status:<br/> &bull; OPEN: means that this payment has been created in finAPI, but not yet submitted to the bank.<br/> &bull; PENDING: means that this payment has been requested at the bank, but not yet executed.<br/> &bull; SUCCESSFUL: means that this payment has been successfully executed.<br/> &bull; NOT_SUCCESSFUL: means that this payment could not be executed successfully.<br/> &bull; DISCARDED: means that this payment was discarded, either because another payment was requested for the same account before this payment was executed and the bank does not support this, or because the bank has rejected the payment even before the execution.
	Status string `json:"status"`
	// Contains the bank's response to the execution of this payment. This field is not set until the payment gets executed. Note that even after the execution of the payment, the field might still not be set, if the bank did not send any response message.
	BankMessage string `json:"bankMessage,omitempty"`
	// Time of when this payment was requested, in the format 'YYYY-MM-DD HH:MM:SS.SSS' (german time)
	RequestDate string `json:"requestDate,omitempty"`
	// Time of when this payment was executed, in the format 'YYYY-MM-DD HH:MM:SS.SSS' (german time)
	ExecutionDate string `json:"executionDate,omitempty"`
}
