/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.93.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Sample data to train categorization
type TrainCategorizationData struct {
	// Set of transaction data (at most 100 transactions at once)
	TransactionData []TrainCategorizationTransactionData `json:"transactionData"`
	// Category identifier
	CategoryId int64 `json:"categoryId"`
}
