/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Cash flows
type CashFlowList struct {
	// Array of cash flows
	CashFlows []CashFlow `json:"cashFlows"`
	// The total income
	TotalIncome float64 `json:"totalIncome"`
	// The total spending
	TotalSpending float64 `json:"totalSpending"`
	// The total balance
	TotalBalance float64 `json:"totalBalance"`
}
