/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.93.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for multi-step authentication data, as passed by the client to finAPI
type MultiStepAuthenticationCallback struct {
	// Hash that was returned in the previous multi-step authentication error.
	Hash string `json:"hash"`
	// Challenge response. Must be set when the previous multi-step authentication error had status 'CHALLENGE_RESPONSE_REQUIRED.
	ChallengeResponse string `json:"challengeResponse,omitempty"`
	// The bank-given ID of the two-step-procedure that should be used for authentication. Must be set when the previous multi-step authentication error had status 'TWO_STEP_PROCEDURE_REQUIRED.
	TwoStepProcedureId string `json:"twoStepProcedureId,omitempty"`
	// Must be passed when the previous multi-step authentication error had status 'REDIRECT_REQUIRED'. The value must consist of the complete query parameter list that was contained in the received redirect from the bank.
	RedirectCallback string `json:"redirectCallback,omitempty"`
	// Must be passed when the previous multi-step authentication error had status 'DECOUPLED_AUTH_REQUIRED' or 'DECOUPLED_AUTH_IN_PROGRESS'. The field represents the state of the decoupled authentication meaning that when it's set to 'true', the end-user has completed the authentication process on bank's side.
	DecoupledCallback bool `json:"decoupledCallback,omitempty"`
}
