/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for direct debit creation parameters
type CreateDirectDebitParams struct {
	// Identifier of the account that should be used for the payment.
	AccountId int64 `json:"accountId"`
	// Type of the direct debit; either <code>BASIC</code> or <code>B2B</code> (Business-To-Business).
	DirectDebitType string `json:"directDebitType"`
	// Sequence type of the direct debit. Possible values:<br/><br/>&bull; <code>OOFF</code> - means that this is a one-time direct debit order<br/>&bull; <code>FRST</code> - means that this is the first in a row of multiple direct debit orders<br/>&bull; <code>RCUR</code> - means that this is one (but not the first or final) within a row of multiple direct debit orders<br/>&bull; <code>FNAL</code> - means that this is the final in a row of multiple direct debit orders<br/><br/>
	SequenceType string `json:"sequenceType"`
	// List of direct debit orders (may contain at most 15000 items). Please note that collective direct debit may not always be supported.
	DirectDebits []DirectDebitOrderParams `json:"directDebits"`
	// This field is only relevant when you pass multiple orders. It determines whether the orders should be processed by the bank as one collective booking (in case of 'false'), or as single bookings (in case of 'true'). Note that it is subject to the bank whether it will regard the field. Default value is 'false'.
	SingleBooking bool `json:"singleBooking,omitempty"`
	// Execution date for the direct debit(s), in the format 'YYYY-MM-DD'. May not be in the past.
	ExecutionDate string `json:"executionDate"`
}
