/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.71.0.b1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Request password change parameters
type RequestPasswordChangeParams struct {
	// User identifier
	UserId string `json:"userId"`
}
