/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.71.0.b1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Response type when a service call was not successful. Contains details about the error(s) that occurred.
type ErrorMessage struct {
	// List of errors
	Errors []ErrorDetails `json:"errors"`
	// Server date of when the error(s) occurred, in the format YYYY-MM-DD HH:MM:SS.SSS
	Date string `json:"date"`
	// ID of the request that caused this error. This is either what you have passed for the header 'X-REQUEST-ID', or an auto-generated ID in case you didn't pass any value for that header.
	RequestId string `json:"requestId,omitempty"`
	// The service endpoint that was called
	Endpoint string `json:"endpoint"`
	// Information about the authorization context of the service call
	AuthContext string `json:"authContext"`
	// BLZ and name (in format \"<BLZ> - <name>\") of a bank that was used for the original request
	Bank string `json:"bank,omitempty"`
}
