/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for data of multiple transactions
type TransactionList struct {
	// List of transactions
	Transactions []Transaction `json:"transactions"`
}
