/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Category data
type Category struct {
	// Category identifier.<br/><br/>NOTE: Do NOT assume that the identifiers of the global finAPI categories are the same across different finAPI environments. In fact, the identifiers may change whenever a new finAPI version is released, even within the same environment. The identifiers are meant to be used for references within the finAPI services only, but not for hard-coding them in your application. If you need to hard-code the usage of a certain global category within your application, please instead refer to the category name. Also, please make sure to check the 'isCustom' flag, which is false for all global categories (if you are not regarding this flag, you might end up referring to a user-specific category, and not the global category).
	Id int64 `json:"id"`
	// Category name
	Name string `json:"name"`
	// Identifier of the parent category (if a parent category exists)
	ParentId int64 `json:"parentId,omitempty"`
	// Name of the parent category (if a parent category exists)
	ParentName string `json:"parentName,omitempty"`
	// Whether the category is a finAPI global category (in which case this field will be false), or the category was created by a user (in which case this field will be true)
	IsCustom bool `json:"isCustom"`
	// List of sub-categories identifiers (if any exist)
	Children []int64 `json:"children,omitempty"`
}
