/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.71.0.b1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Container for users information with paging info
type PageableUserInfoList struct {
	// List of users information
	Users []UserInfo `json:"users"`
	// Information for pagination
	Paging *Paging `json:"paging"`
}
