/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.71.0.b1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Container for a label's data
type Label struct {
	// Label identifier
	Id int64 `json:"id"`
	// Label name
	Name string `json:"name"`
}
