/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Data for a mock bank connection update
type MockBankConnectionUpdate struct {
	// Bank connection identifier
	BankConnectionId int64 `json:"bankConnectionId"`
	// Banking interface to update. If not specified, then first available interface in bank connection will be used.
	Interface_ string `json:"interface,omitempty"`
	// Whether to simulate the case that the update fails due to incorrect banking credentials. Note that there is no real communication to any bank server involved, so you won't lock your accounts when enabling this flag. Default value is 'false'.
	SimulateBankLoginError bool `json:"simulateBankLoginError,omitempty"`
	// Mock accounts data. Note that for accounts that exist in a bank connection but that you do not specify in this list, the service will act like those accounts are not received by the bank servers. This means that any accounts that you do not specify here will be marked as deprecated. If you do not specify this list at all, all accounts in the bank connection will be marked as deprecated.
	MockAccountsData []MockAccountData `json:"mockAccountsData,omitempty"`
}
