/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Identifiers params
type KeywordRuleIdentifiersParams struct {
	// List of identifiers
	Ids []int64 `json:"ids"`
}
