/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// A container for the bank certificate's data
type TppCertificate struct {
	// A certificate identifier.
	Id int64 `json:"id"`
	// Type of certificate.
	CertificateType string `json:"certificateType"`
	// Optional label of certificate.
	Label string `json:"label,omitempty"`
	// Valid from date in the format 'YYYY-MM-DD'.
	ValidFrom string `json:"validFrom,omitempty"`
	// Valid until date in the format 'YYYY-MM-DD'.
	ValidUntil string `json:"validUntil,omitempty"`
}
