/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for interface removal parameters
type RemoveInterfaceParams struct {
	// Bank connection identifier
	BankConnectionId int64 `json:"bankConnectionId"`
	// The interface which you want to remove.
	Interface_ string `json:"interface,omitempty"`
}
