/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.79.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Set of identifiers (in ascending order)
type IdentifierList struct {
	// Set of identifiers (in ascending order)
	Identifiers []int64 `json:"identifiers,omitempty"`
}
