/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.79.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Label's name
type LabelParams struct {
	// Label's name. Maximum length is 288.
	Name string `json:"name"`
}
