/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.79.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for IBAN rule information with paging info
type PageableIbanRuleList struct {
	// List of iban rules information
	IbanRules []IbanRule `json:"ibanRules"`
	// Information for pagination
	Paging *Paging `json:"paging"`
}
