/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.79.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// User identifiers params
type UserIdentifiersParams struct {
	// List of user identifiers
	UserIds []string `json:"userIds"`
}
