/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

type ClearingAccountData struct {
	// Technical identifier of the clearing account
	ClearingAccountId string `json:"clearingAccountId"`
	// Name of the clearing account
	ClearingAccountName string `json:"clearingAccountName"`
}
