/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Params for creation IBAN rules
type IbanRulesParams struct {
	// IBAN rule definitions. The minimum number of rule definitions is 1. The maximum number of rule definitions is 100.
	IbanRules []IbanRuleParams `json:"ibanRules"`
}
