/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.71.0.b1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Container for data of multiple transactions
type TransactionList struct {
	// Array of transactions
	Transactions []Transaction `json:"transactions"`
}
