/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.71.0.b1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type BadCredentialsError struct {
	// Error type
	Error_ string `json:"error"`
	// Error description
	ErrorDescription string `json:"error_description"`
}
