/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for parameters for the execution of a submitted SEPA money transfer order
type ExecuteSepaMoneyTransferParams struct {
	// Identifier of the bank account that you want to transfer money from
	AccountId int64 `json:"accountId"`
	// Banking TAN that the user received from the bank for executing the money transfer order. The field is required if you are licensed to perform SEPA money transfers yourself. Otherwise, i.e. when finAPI's web form flow is required, the web form will deal with executing the service itself.
	BankingTan string `json:"bankingTan,omitempty"`
}
