/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.93.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Parameters of IBAN rule
type IbanRuleParams struct {
	// IBAN (case-insensitive)
	Iban string `json:"iban"`
	// ID of the category that this rule should assign to the matching transactions
	CategoryId int64 `json:"categoryId"`
	// Direction for the rule. 'Income' means that the rule applies to transactions with a positive amount only, 'Spending' means it applies to transactions with a negative amount only. 'Both' means that it applies to both kind of transactions. Note that in case of 'Both', finAPI will create two individual rules (one with direction 'Income' and one with direction 'Spending').
	Direction string `json:"direction"`
}
