/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for keyword rules
type KeywordRuleList struct {
	// List of keyword rules
	KeywordRules []KeywordRule `json:"keywordRules"`
}
