/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Execute password change parameters
type ExecutePasswordChangeParams struct {
	// User identifier
	UserId string `json:"userId"`
	// User's new password. Minimum length is 6, and maximum length is 128.
	Password string `json:"password"`
	// Decrypted password change token (the token that you received from the /users/requestPasswordChange service, decrypted with your data decryption key)
	PasswordChangeToken string `json:"passwordChangeToken"`
}
