/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.79.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Payment resources with paging information
type PageablePaymentResources struct {
	// List of received account payments
	Payments []Payment `json:"payments"`
	// Information for pagination
	Paging *Paging `json:"paging"`
}
