/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: 1.106.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Container for bank certificate information with paging info
type PageableTppCertificateList struct {
	// List of certificates
	TppCertificates []TppCertificate `json:"tppCertificates"`
	// Information for pagination
	Paging *Paging `json:"paging"`
}
