/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.79.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package finapi

// Parameters for changing client credentials
type ChangeClientCredentialsParams struct {
	// client_id of the client that you want to change the secret for
	ClientId string `json:"clientId"`
	// Old (=current) client_secret
	OldClientSecret string `json:"oldClientSecret"`
	// New client_secret. Required length is 36. Allowed symbols: Digits (0 through 9), lower-case and upper-case letters (A through Z), and the dash symbol (\"-\").
	NewClientSecret string `json:"newClientSecret"`
}
